---
apiVersion: v1
data:
  uuid: MGMzYzE4YjQtMTgxNy00YmUxLTg3NjYtYTk5NWQxMTI0YmMx
immutable: true
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: srikar-mgmt
    clusterctl.cluster.x-k8s.io/move: ""
  name: prism-central-metadata
  namespace: default
type: Opaque
