---
apiVersion: v1
data:
  additionalTrustBundle: ""
  insecure: dHJ1ZQ==
  password: S3ViZVBvZHNAMzIx
  prismURL: aHR0cHM6Ly8xOTAuMTcwLjEwLjIwOTo5NDQw
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    dkp-infrastructure-provider-type: nutanix-secret
  name: global-nutanix-credentials
  namespace: capx-system
type: Opaque
