apiVersion: v1
kind: Secret
metadata:
  name: pc-files-secret
  namespace: ntnx-system
type: Opaque
stringData:
  key: "190.170.11.211:admin:Nutanix/4all!"
  files-key: "FILE-SERVER.kuberox.net:mgmt:mgmt"
