apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwx-pvc
  namespace: srikar
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-pc-sc
  resources:
    requests:
      storage: 10Gi
